Internal Server Error: /comments/create/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Python27\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Python27\lib\site-packages\rest_framework\views.py", line 403, in dispatch
    response = self.handle_exception(exc)
  File "D:\Python27\lib\site-packages\rest_framework\views.py", line 400, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\Python27\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "G:\py_work_space\YoYoProject\yyCommentCenter\views.py", line 78, in createComment
    return Response(serializer.data(),status=status.HTTP_200_OK)
  File "G:\py_work_space\YoYoProject\yyCommentCenter\serializers.py", line 22, in data
    return json.dumps(dict)
  File "D:\Python27\lib\json\__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "D:\Python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "D:\Python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "D:\Python27\lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.datetime(2014, 11, 28, 15, 27, 46, 433000) is not JSON serializable
Not Found: /favicon.ico
Internal Server Error: /comments/show/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Python27\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Python27\lib\site-packages\rest_framework\views.py", line 403, in dispatch
    response = self.handle_exception(exc)
  File "D:\Python27\lib\site-packages\rest_framework\views.py", line 400, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\Python27\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "G:\py_work_space\YoYoProject\yyCommentCenter\views.py", line 140, in showComments
    staffList = paginator.page(pageIndex)
  File "D:\Python27\lib\site-packages\django\core\paginator.py", line 50, in page
    number = self.validate_number(number)
  File "D:\Python27\lib\site-packages\django\core\paginator.py", line 39, in validate_number
    if number > self.num_pages:
  File "D:\Python27\lib\site-packages\django\core\paginator.py", line 86, in _get_num_pages
    if self.count == 0 and not self.allow_empty_first_page:
  File "D:\Python27\lib\site-packages\django\core\paginator.py", line 72, in _get_count
    self._count = self.object_list.count()
  File "D:\Python27\lib\site-packages\mongoengine\queryset\queryset.py", line 108, in count
    self._len = super(QuerySet, self).count(with_limit_and_skip)
  File "D:\Python27\lib\site-packages\mongoengine\queryset\base.py", line 339, in count
    return self._cursor.count(with_limit_and_skip=with_limit_and_skip)
  File "D:\Python27\lib\site-packages\mongoengine\queryset\base.py", line 1182, in _cursor
    self._cursor_obj = self._collection.find(self._query,
  File "D:\Python27\lib\site-packages\mongoengine\queryset\base.py", line 1215, in _query
    self._mongo_query = self._query_obj.to_query(self._document)
  File "D:\Python27\lib\site-packages\mongoengine\queryset\visitor.py", line 92, in to_query
    query = query.accept(QueryCompilerVisitor(document))
  File "D:\Python27\lib\site-packages\mongoengine\queryset\visitor.py", line 157, in accept
    return visitor.visit_query(self)
  File "D:\Python27\lib\site-packages\mongoengine\queryset\visitor.py", line 80, in visit_query
    return transform.query(self.document, **query.query)
  File "D:\Python27\lib\site-packages\mongoengine\queryset\transform.py", line 87, in query
    value = field.prepare_query_value(op, value)
  File "D:\Python27\lib\site-packages\mongoengine\fields.py", line 196, in prepare_query_value
    return int(value)
ValueError: invalid literal for int() with base 10: '547820f94b69b2263c9cd8d2'
Not Found: /chat/
Not Found: /favicon.ico
Not Found: /chat/
Not Found: /chat/
Not Found: /
Not Found: /favicon.ico
Not Found: /static/rest_framework/css/bootstrap.min.css
Not Found: /static/rest_framework/css/prettify.css
Not Found: /static/rest_framework/css/default.css
Not Found: /static/rest_framework/js/jquery-1.8.1-min.js
Not Found: /static/rest_framework/js/bootstrap.min.js
Not Found: /static/rest_framework/css/bootstrap-tweaks.css
Not Found: /static/rest_framework/js/default.js
Not Found: /static/rest_framework/js/prettify-min.js
Not Found: /static/rest_framework/css/bootstrap.min.css
Not Found: /static/rest_framework/css/bootstrap-tweaks.css
Not Found: /static/rest_framework/css/prettify.css
Not Found: /static/rest_framework/js/prettify-min.js
Not Found: /static/rest_framework/js/bootstrap.min.js
Not Found: /static/rest_framework/js/jquery-1.8.1-min.js
Not Found: /static/rest_framework/css/default.css
Not Found: /static/rest_framework/js/default.js
Not Found: /favicon.ico
Not Found: /favicon.ico
Internal Server Error: /userCenter/register/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Python27\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Python27\lib\site-packages\rest_framework\views.py", line 403, in dispatch
    response = self.handle_exception(exc)
  File "D:\Python27\lib\site-packages\rest_framework\views.py", line 400, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\Python27\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "G:\py_work_space\YoYoProject\yyUserCenter\views.py", line 140, in register
    return Response(userInfoSerializer.errors,status=status.HTTP_400_BAD_REQUEST)
UnboundLocalError: local variable 'userInfoSerializer' referenced before assignment
Not Found: /static/rest_framework/css/bootstrap.min.css
Not Found: /static/rest_framework/css/prettify.css
Not Found: /static/rest_framework/css/default.css
Not Found: /static/rest_framework/js/jquery-1.8.1-min.js
Not Found: /static/rest_framework/js/prettify-min.js
Not Found: /static/rest_framework/js/default.js
Not Found: /static/rest_framework/css/bootstrap-tweaks.css
Not Found: /static/rest_framework/js/bootstrap.min.js
Not Found: /static/rest_framework/css/bootstrap.min.css
Not Found: /static/rest_framework/css/default.css
Not Found: /static/rest_framework/js/jquery-1.8.1-min.js
Not Found: /static/rest_framework/js/bootstrap.min.js
Not Found: /static/rest_framework/css/bootstrap-tweaks.css
Not Found: /static/rest_framework/js/default.js
Not Found: /static/rest_framework/css/prettify.css
Not Found: /static/rest_framework/js/prettify-min.js
Not Found: /static/rest_framework/css/bootstrap.min.css
Not Found: /static/rest_framework/css/prettify.css
Not Found: /static/rest_framework/css/default.css
Not Found: /static/rest_framework/js/jquery-1.8.1-min.js
Not Found: /static/rest_framework/js/bootstrap.min.js
Not Found: /static/rest_framework/js/default.js
Not Found: /static/rest_framework/css/bootstrap-tweaks.css
Not Found: /static/rest_framework/js/prettify-min.js
Not Found: /static/rest_framework/css/bootstrap.min.css
Not Found: /static/rest_framework/css/bootstrap-tweaks.css
Not Found: /static/rest_framework/css/prettify.css
Not Found: /static/rest_framework/css/default.css
Not Found: /static/rest_framework/js/jquery-1.8.1-min.js
Not Found: /static/rest_framework/js/bootstrap.min.js
Not Found: /static/rest_framework/js/default.js
Not Found: /static/rest_framework/js/prettify-min.js
Not Found: /static/rest_framework/css/bootstrap.min.css
Not Found: /static/rest_framework/css/default.css
Not Found: /static/rest_framework/css/bootstrap-tweaks.css
Not Found: /static/rest_framework/js/jquery-1.8.1-min.js
Not Found: /static/rest_framework/js/bootstrap.min.js
Not Found: /static/rest_framework/css/prettify.css
Not Found: /static/rest_framework/js/prettify-min.js
Not Found: /static/rest_framework/js/default.js
Not Found: /static/rest_framework/css/bootstrap-tweaks.css
Not Found: /static/rest_framework/css/bootstrap.min.css
Not Found: /static/rest_framework/css/prettify.css
Not Found: /static/rest_framework/js/jquery-1.8.1-min.js
Not Found: /static/rest_framework/css/default.css
Not Found: /static/rest_framework/js/bootstrap.min.js
Not Found: /static/rest_framework/js/prettify-min.js
Not Found: /static/rest_framework/js/default.js
Not Found: /static/rest_framework/css/bootstrap.min.css
Not Found: /static/rest_framework/css/prettify.css
Not Found: /static/rest_framework/css/default.css
Not Found: /static/rest_framework/js/jquery-1.8.1-min.js
Not Found: /static/rest_framework/js/bootstrap.min.js
Not Found: /static/rest_framework/js/default.js
Not Found: /static/rest_framework/css/bootstrap-tweaks.css
Not Found: /static/rest_framework/js/prettify-min.js
Not Found: /static/rest_framework/css/bootstrap.min.css
Not Found: /static/rest_framework/css/default.css
Not Found: /static/rest_framework/js/jquery-1.8.1-min.js
Not Found: /static/rest_framework/js/bootstrap.min.js
Not Found: /static/rest_framework/css/prettify.css
Not Found: /static/rest_framework/js/default.js
Not Found: /static/rest_framework/css/bootstrap-tweaks.css
Not Found: /static/rest_framework/js/prettify-min.js
Not Found: /userCenter/register/form=json
Not Found: /static/rest_framework/css/bootstrap.min.css
Not Found: /static/rest_framework/css/default.css
Not Found: /static/rest_framework/css/bootstrap-tweaks.css
Not Found: /static/rest_framework/css/prettify.css
Not Found: /static/rest_framework/js/prettify-min.js
Not Found: /static/rest_framework/js/jquery-1.8.1-min.js
Not Found: /static/rest_framework/js/bootstrap.min.js
Not Found: /static/rest_framework/js/default.js
Not Found: /hello-tornado
Not Found: /favicon.ico
Not Found: /
Not Found: /static/rest_framework/css/bootstrap.min.css
Not Found: /static/rest_framework/css/default.css
Not Found: /static/rest_framework/css/bootstrap-tweaks.css
Not Found: /static/rest_framework/js/jquery-1.8.1-min.js
Not Found: /static/rest_framework/css/prettify.css
Not Found: /static/rest_framework/js/prettify-min.js
Not Found: /static/rest_framework/js/bootstrap.min.js
Not Found: /static/rest_framework/js/default.js
Not Found: /WebSocket/12323232
Internal Server Error: /tag/createTag
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 87, in get_response
    response = middleware_method(request)
  File "D:\Python27\lib\site-packages\django\middleware\common.py", line 82, in process_request
    "settings.") % (new_url[0], new_url[1]))
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/tag/createTag/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
Internal Server Error: /tag/createTag/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Python27\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Python27\lib\site-packages\rest_framework\views.py", line 403, in dispatch
    response = self.handle_exception(exc)
  File "D:\Python27\lib\site-packages\rest_framework\views.py", line 400, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\Python27\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "G:\py_work_space\YoYoProject\yyTagManager\views.py", line 55, in createTag
    tagInfo.save()
  File "D:\Python27\lib\site-packages\django\db\models\base.py", line 591, in save
    force_update=force_update, update_fields=update_fields)
  File "D:\Python27\lib\site-packages\django\db\models\base.py", line 619, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "D:\Python27\lib\site-packages\django\db\models\base.py", line 700, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "D:\Python27\lib\site-packages\django\db\models\base.py", line 733, in _do_insert
    using=using, raw=raw)
  File "D:\Python27\lib\site-packages\django\db\models\manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Python27\lib\site-packages\django\db\models\query.py", line 921, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "D:\Python27\lib\site-packages\django\db\models\sql\compiler.py", line 920, in execute_sql
    cursor.execute(sql, params)
  File "D:\Python27\lib\site-packages\django\db\backends\utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "D:\Python27\lib\site-packages\django\db\backends\utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "D:\Python27\lib\site-packages\django\db\utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "D:\Python27\lib\site-packages\django\db\backends\utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "D:\Python27\lib\site-packages\django\db\backends\mysql\base.py", line 128, in execute
    return self.cursor.execute(query, args)
  File "D:\Python27\lib\site-packages\MySQLdb\cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "D:\Python27\lib\site-packages\MySQLdb\connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1146, "Table 'yy_db.yytagmanager_yytaginfo' doesn't exist")
Internal Server Error: /tag/viewTag
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 87, in get_response
    response = middleware_method(request)
  File "D:\Python27\lib\site-packages\django\middleware\common.py", line 72, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 619, in is_valid_path
    resolve(path, urlconf)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 494, in resolve
    return get_resolver(urlconf).resolve(path)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 343, in resolve
    for pattern in self.url_patterns:
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 372, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 366, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "D:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "G:\py_work_space\YoYoProject\YoYoProject\urls.py", line 14, in <module>
    url(r'^tag/',include('yyTagManager.urls')),
  File "D:\Python27\lib\site-packages\django\conf\urls\__init__.py", line 28, in include
    urlconf_module = import_module(urlconf_module)
  File "D:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "G:\py_work_space\YoYoProject\yyTagManager\urls.py", line 4, in <module>
    from yyTagManager import views
  File "G:\py_work_space\YoYoProject\yyTagManager\views.py", line 11, in <module>
    from yyTagManager.serializers import YYTagInfoSerializer,\
  File "G:\py_work_space\YoYoProject\yyTagManager\serializers.py", line 12, in <module>
    class YYPaginatedTagInfoSerializer(pagination.PaginationSerializer):
AttributeError: 'function' object has no attribute 'PaginationSerializer'
Internal Server Error: /tag/createTag/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Python27\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Python27\lib\site-packages\rest_framework\views.py", line 403, in dispatch
    response = self.handle_exception(exc)
  File "D:\Python27\lib\site-packages\rest_framework\views.py", line 400, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\Python27\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "G:\py_work_space\YoYoProject\yyTagManager\views.py", line 74, in createTag
    tagInfo.save()
  File "D:\Python27\lib\site-packages\django\db\models\base.py", line 591, in save
    force_update=force_update, update_fields=update_fields)
  File "D:\Python27\lib\site-packages\django\db\models\base.py", line 619, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "D:\Python27\lib\site-packages\django\db\models\base.py", line 700, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "D:\Python27\lib\site-packages\django\db\models\base.py", line 733, in _do_insert
    using=using, raw=raw)
  File "D:\Python27\lib\site-packages\django\db\models\manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Python27\lib\site-packages\django\db\models\query.py", line 921, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "D:\Python27\lib\site-packages\django\db\models\sql\compiler.py", line 920, in execute_sql
    cursor.execute(sql, params)
  File "D:\Python27\lib\site-packages\django\db\backends\utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "D:\Python27\lib\site-packages\django\db\backends\utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "D:\Python27\lib\site-packages\django\db\utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "D:\Python27\lib\site-packages\django\db\backends\utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "D:\Python27\lib\site-packages\django\db\backends\mysql\base.py", line 128, in execute
    return self.cursor.execute(query, args)
  File "D:\Python27\lib\site-packages\MySQLdb\cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "D:\Python27\lib\site-packages\MySQLdb\connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1146, "Table 'yy_db.yy_tag_info' doesn't exist")
Internal Server Error: /tag/createTag/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Python27\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Python27\lib\site-packages\rest_framework\views.py", line 403, in dispatch
    response = self.handle_exception(exc)
  File "D:\Python27\lib\site-packages\rest_framework\views.py", line 400, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\Python27\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "G:\py_work_space\YoYoProject\yyTagManager\views.py", line 77, in createTag
    return Response(tagInfoSerializer.data, status=status.HTTP_200_OK)
  File "D:\Python27\lib\site-packages\rest_framework\serializers.py", line 576, in data
    self._data = self.to_native(obj)
  File "D:\Python27\lib\site-packages\rest_framework\serializers.py", line 350, in to_native
    for field_name, field in self.fields.items():
  File "D:\Python27\lib\site-packages\django\utils\functional.py", line 55, in __get__
    res = instance.__dict__[self.func.__name__] = self.func(instance)
  File "D:\Python27\lib\site-packages\rest_framework\serializers.py", line 217, in fields
    return self.get_fields()
  File "D:\Python27\lib\site-packages\rest_framework\serializers.py", line 250, in get_fields
    new[key] = ret[key]
KeyError: 'pk'
Internal Server Error: /tag/createTag/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Python27\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Python27\lib\site-packages\rest_framework\views.py", line 403, in dispatch
    response = self.handle_exception(exc)
  File "D:\Python27\lib\site-packages\rest_framework\views.py", line 400, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\Python27\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "G:\py_work_space\YoYoProject\yyTagManager\views.py", line 77, in createTag
    return Response(tagInfoSerializer.data, status=status.HTTP_200_OK)
AttributeError: 'NoneType' object has no attribute 'HTTP_200_OK'
Internal Server Error: /tag/viewTag/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Python27\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Python27\lib\site-packages\rest_framework\views.py", line 403, in dispatch
    response = self.handle_exception(exc)
  File "D:\Python27\lib\site-packages\rest_framework\views.py", line 400, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\Python27\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "G:\py_work_space\YoYoProject\yyTagManager\views.py", line 100, in viewTagList
    return ErrorResponse("No Content",status=status.HTTP_204_NO_CONTENT)
TypeError: __init__() got an unexpected keyword argument 'status'
Internal Server Error: /tag/refreshTag/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Python27\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Python27\lib\site-packages\rest_framework\views.py", line 403, in dispatch
    response = self.handle_exception(exc)
  File "D:\Python27\lib\site-packages\rest_framework\views.py", line 400, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\Python27\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "G:\py_work_space\YoYoProject\yyTagManager\views.py", line 148, in refreshToMem
    cache.set("test_key","value1")
  File "D:\Python27\lib\site-packages\django_redis\cache.py", line 25, in _decorator
    return method(self, *args, **kwargs)
  File "D:\Python27\lib\site-packages\django_redis\cache.py", line 59, in set
    return self.client.set(*args, **kwargs)
  File "D:\Python27\lib\site-packages\django_redis\client\default.py", line 152, in set
    return client.setex(key, int(timeout), value)
  File "D:\Python27\lib\site-packages\redis\client.py", line 1076, in setex
    return self.execute_command('SETEX', name, time, value)
  File "D:\Python27\lib\site-packages\redis\client.py", line 564, in execute_command
    connection.send_command(*args)
  File "D:\Python27\lib\site-packages\redis\connection.py", line 556, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "D:\Python27\lib\site-packages\redis\connection.py", line 532, in send_packed_command
    self.connect()
  File "D:\Python27\lib\site-packages\redis\connection.py", line 440, in connect
    self.on_connect()
  File "D:\Python27\lib\site-packages\redis\connection.py", line 514, in on_connect
    if nativestr(self.read_response()) != 'OK':
  File "D:\Python27\lib\site-packages\redis\connection.py", line 574, in read_response
    raise response
ResponseError: NOAUTH Authentication required.
Internal Server Error: /tag/refreshTag/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Python27\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Python27\lib\site-packages\rest_framework\views.py", line 403, in dispatch
    response = self.handle_exception(exc)
  File "D:\Python27\lib\site-packages\rest_framework\views.py", line 400, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\Python27\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "G:\py_work_space\YoYoProject\yyTagManager\views.py", line 148, in refreshToMem
    cache.set("test_key","value1")
  File "D:\Python27\lib\site-packages\django_redis\cache.py", line 25, in _decorator
    return method(self, *args, **kwargs)
  File "D:\Python27\lib\site-packages\django_redis\cache.py", line 59, in set
    return self.client.set(*args, **kwargs)
  File "D:\Python27\lib\site-packages\django_redis\client\default.py", line 152, in set
    return client.setex(key, int(timeout), value)
  File "D:\Python27\lib\site-packages\redis\client.py", line 1076, in setex
    return self.execute_command('SETEX', name, time, value)
  File "D:\Python27\lib\site-packages\redis\client.py", line 564, in execute_command
    connection.send_command(*args)
  File "D:\Python27\lib\site-packages\redis\connection.py", line 556, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "D:\Python27\lib\site-packages\redis\connection.py", line 532, in send_packed_command
    self.connect()
  File "D:\Python27\lib\site-packages\redis\connection.py", line 440, in connect
    self.on_connect()
  File "D:\Python27\lib\site-packages\redis\connection.py", line 514, in on_connect
    if nativestr(self.read_response()) != 'OK':
  File "D:\Python27\lib\site-packages\redis\connection.py", line 574, in read_response
    raise response
ResponseError: NOAUTH Authentication required.
Internal Server Error: /tag/refreshTag/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Python27\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Python27\lib\site-packages\rest_framework\views.py", line 403, in dispatch
    response = self.handle_exception(exc)
  File "D:\Python27\lib\site-packages\rest_framework\views.py", line 400, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\Python27\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "G:\py_work_space\YoYoProject\yyTagManager\views.py", line 148, in refreshToMem
    cache.set("test_key","value1")
  File "D:\Python27\lib\site-packages\django_redis\cache.py", line 25, in _decorator
    return method(self, *args, **kwargs)
  File "D:\Python27\lib\site-packages\django_redis\cache.py", line 59, in set
    return self.client.set(*args, **kwargs)
  File "D:\Python27\lib\site-packages\django_redis\client\default.py", line 152, in set
    return client.setex(key, int(timeout), value)
  File "D:\Python27\lib\site-packages\redis\client.py", line 1076, in setex
    return self.execute_command('SETEX', name, time, value)
  File "D:\Python27\lib\site-packages\redis\client.py", line 564, in execute_command
    connection.send_command(*args)
  File "D:\Python27\lib\site-packages\redis\connection.py", line 556, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "D:\Python27\lib\site-packages\redis\connection.py", line 532, in send_packed_command
    self.connect()
  File "D:\Python27\lib\site-packages\redis\connection.py", line 440, in connect
    self.on_connect()
  File "D:\Python27\lib\site-packages\redis\connection.py", line 514, in on_connect
    if nativestr(self.read_response()) != 'OK':
  File "D:\Python27\lib\site-packages\redis\connection.py", line 574, in read_response
    raise response
ResponseError: NOAUTH Authentication required.
Internal Server Error: /
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 343, in resolve
    for pattern in self.url_patterns:
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 372, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 366, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "D:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "G:\py_work_space\YoYoProject\YoYoProject\urls.py", line 13, in <module>
    url(r'^comments/',include('yyCommentCenter.urls')),
  File "D:\Python27\lib\site-packages\django\conf\urls\__init__.py", line 28, in include
    urlconf_module = import_module(urlconf_module)
  File "D:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "G:\py_work_space\YoYoProject\yyCommentCenter\urls.py", line 4, in <module>
    from yyCommentCenter import views
  File "G:\py_work_space\YoYoProject\yyCommentCenter\views.py", line 10, in <module>
    from YoYoProject.errorResponse import ErrorResponse
ImportError: No module named errorResponse
Internal Server Error: /crm/index
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 87, in get_response
    response = middleware_method(request)
  File "D:\Python27\lib\site-packages\django\middleware\common.py", line 72, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 619, in is_valid_path
    resolve(path, urlconf)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 494, in resolve
    return get_resolver(urlconf).resolve(path)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 343, in resolve
    for pattern in self.url_patterns:
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 372, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 366, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "D:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "G:\py_work_space\YoYoProject\YoYoProject\urls.py", line 13, in <module>
    url(r'^comments/',include('yyCommentCenter.urls')),
  File "D:\Python27\lib\site-packages\django\conf\urls\__init__.py", line 28, in include
    urlconf_module = import_module(urlconf_module)
  File "D:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "G:\py_work_space\YoYoProject\yyCommentCenter\urls.py", line 4, in <module>
    from yyCommentCenter import views
  File "G:\py_work_space\YoYoProject\yyCommentCenter\views.py", line 10, in <module>
    from YoYoProject.errorResponse import ErrorResponse
ImportError: No module named errorResponse
Not Found: /user/userList/
Not Found: /crm/user/userList/
Not Found: /crm/user/userList/
Not Found: /crm/user/userList/
Not Found: /
Internal Server Error: /crm/user/userList/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\py_work_space\YoYoProject\yyCRM\views.py", line 21, in crmUserList
    pageCount = form.cleaned_data['pageCount']
KeyError: 'pageCount'
Forbidden (CSRF token missing or incorrect.): /crm/user/userList/
Forbidden (CSRF token missing or incorrect.): /crm/user/userList/
Forbidden (CSRF token missing or incorrect.): /crm/user/userList/
Forbidden (CSRF token missing or incorrect.): /crm/user/userList/
Internal Server Error: /crm/user/userList/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "G:\py_work_space\YoYoProject\yyCRM\views.py", line 24, in crmUserList
    pageIndex = form.cleaned_data['pageIndex']
AttributeError: 'QueryUserForm' object has no attribute 'cleaned_data'
Internal Server Error: /crm/user/userList/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "G:\py_work_space\YoYoProject\yyCRM\views.py", line 24, in crmUserList
    pageIndex = form.cleaned_data['pageIndex']
AttributeError: 'QueryUserForm' object has no attribute 'cleaned_data'
Internal Server Error: /crm/user/userList/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "G:\py_work_space\YoYoProject\yyCRM\views.py", line 24, in crmUserList
    pageIndex = form.cleaned_data['pageIndex']
AttributeError: 'QueryUserForm' object has no attribute 'cleaned_data'
Internal Server Error: /crm/user/userList/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "G:\py_work_space\YoYoProject\yyCRM\views.py", line 24, in crmUserList
    pageIndex = form.cleaned_data['pageIndex']
AttributeError: 'QueryUserForm' object has no attribute 'cleaned_data'
Internal Server Error: /crm/user/userList/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "G:\py_work_space\YoYoProject\yyCRM\views.py", line 24, in crmUserList
    pageIndex = form.cleaned_data['pageIndex']
AttributeError: 'QueryUserForm' object has no attribute 'cleaned_data'
Internal Server Error: /crm/user/userList/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "G:\py_work_space\YoYoProject\yyCRM\views.py", line 24, in crmUserList
    pageIndex = form.cleaned_data['pageIndex']
AttributeError: 'QueryUserForm' object has no attribute 'cleaned_data'
Internal Server Error: /crm/user/userList/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "G:\py_work_space\YoYoProject\yyCRM\views.py", line 24, in crmUserList
    pageIndex = form.cleaned_data['pageIndex']
AttributeError: 'QueryUserForm' object has no attribute 'cleaned_data'
Internal Server Error: /crm/user/userList/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "G:\py_work_space\YoYoProject\yyCRM\views.py", line 24, in crmUserList
    pageIndex = form.cleaned_data['pageIndex']
AttributeError: 'QueryUserForm' object has no attribute 'cleaned_data'
Internal Server Error: /crm/user/userList/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "G:\py_work_space\YoYoProject\yyCRM\views.py", line 24, in crmUserList
    pageIndex = form.cleaned_data['pageIndex']
AttributeError: 'QueryUserForm' object has no attribute 'cleaned_data'
Not Found: /crm/user/userList/
Internal Server Error: /crm/user/userList
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "G:\py_work_space\YoYoProject\yyCRM\views.py", line 24, in crmUserList
    pageIndex = form.cleaned_data['pageIndex']
AttributeError: 'QueryUserForm' object has no attribute 'cleaned_data'
Not Found: /
Internal Server Error: /crm/index/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\py_work_space\YoYoProject\yyCRM\views.py", line 16, in crmIndex
    return render(request, 'index/index.html')
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 48, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 174, in render_to_string
    return t.render(context_instance)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 148, in render
    return self._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 142, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 844, in render
    bit = self.render_node(node, context)
  File "D:\Python27\lib\site-packages\django\template\debug.py", line 80, in render_node
    return node.render(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 104, in render
    compiled_parent = self.get_parent(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 101, in get_parent
    return get_template(parent)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 132, in find_template
    source, display_name = loader(name, dirs)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 44, in __call__
    return self.load_template(template_name, template_dirs)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 50, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 156, in get_template_from_string
    return Template(source, origin, name)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 132, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 162, in compile_string
    return parser.parse()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 288, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 344, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: 'static'
Not Found: /crm/index/test
Not Found: /user/userList/
Not Found: /user/userList/
Not Found: /crm/index/
Internal Server Error: /cms/user/userList
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "G:\py_work_space\YoYoProject\yyCRM\views.py", line 24, in crmUserList
    pageIndex = form.cleaned_data['pageIndex']
AttributeError: 'QueryUserForm' object has no attribute 'cleaned_data'
Internal Server Error: /cms/user/userList
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "G:\py_work_space\YoYoProject\yyCRM\views.py", line 25, in crmUserList
    if form.cleaned_data:
AttributeError: 'QueryUserForm' object has no attribute 'cleaned_data'
Internal Server Error: /cms/user/userList
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "G:\py_work_space\YoYoProject\yyCRM\views.py", line 25, in crmUserList
    if form.cleaned_data and form.cleaned_data.has_key('pageIndex'):
AttributeError: 'QueryUserForm' object has no attribute 'cleaned_data'
Not Found: /crm/user/userList
Not Found: /crm/user/userList
Not Found: /crm/index/
Internal Server Error: /cms/user/userList
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "G:\py_work_space\YoYoProject\yyCRM\views.py", line 25, in crmUserList
    if form.cleaned_data and form.cleaned_data.has_key('pageIndex'):
AttributeError: 'QueryUserForm' object has no attribute 'cleaned_data'
Internal Server Error: /cms/user/userList
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "G:\py_work_space\YoYoProject\yyCRM\views.py", line 28, in crmUserList
    if form.cleaned_data and form.cleaned_data.has_key('pageIndex'):
AttributeError: 'QueryUserForm' object has no attribute 'cleaned_data'
Internal Server Error: /cms/user/userList
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 130, in get_response
    % (callback.__module__, view_name))
ValueError: The view yyCRM.views.crmUserList didn't return an HttpResponse object. It returned None instead.
Not Found: /
Internal Server Error: /cms/user/userList
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "G:\py_work_space\YoYoProject\yyCRM\views.py", line 65, in cmsUserList
    return render(request, 'userCRM/userList.html', {'userListPage':userListPage})
UnboundLocalError: local variable 'userListPage' referenced before assignment
Internal Server Error: /cms/user/viewUser
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "G:\py_work_space\YoYoProject\yyCRM\views.py", line 33, in cmsViewUser
    return render(request, 'userCMS/viewUser.html',{'user':user})
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 48, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 170, in render_to_string
    t = get_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 144, in get_template
    template, origin = find_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 132, in find_template
    source, display_name = loader(name, dirs)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 44, in __call__
    return self.load_template(template_name, template_dirs)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 50, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 156, in get_template_from_string
    return Template(source, origin, name)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 132, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 162, in compile_string
    return parser.parse()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 264, in parse
    self.empty_variable(token)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 335, in empty_variable
    raise self.error(token, "Empty variable tag")
TemplateSyntaxError: Empty variable tag
Not Found: /cms/user/url
Not Found: /cms/user/url
Not Found: /cms/user/url
Not Found: /cms/user/url
Not Found: /cms/user/url
Internal Server Error: /cms/user/viewUser
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "G:\py_work_space\YoYoProject\yyCRM\views.py", line 33, in cmsViewUser
    return render(request, 'userCMS/viewUser.html',{'user':user})
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 48, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 178, in render_to_string
    return t.render(context_instance)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 148, in render
    return self._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 142, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 844, in render
    bit = self.render_node(node, context)
  File "D:\Python27\lib\site-packages\django\template\debug.py", line 80, in render_node
    return node.render(context)
  File "D:\Python27\lib\site-packages\django\template\debug.py", line 90, in render
    output = self.filter_expression.resolve(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 596, in resolve
    obj = self.var.resolve(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 734, in resolve
    value = self._resolve_lookup(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 788, in _resolve_lookup
    current = current()
  File "G:\py_work_space\YoYoProject\yyUserCenter\models.py", line 65, in getIconURL
    url = yyMongoImgManager.imgService.getImgUrl(self.iconID)
  File "G:\py_work_space\YoYoProject\yyMongoImgManager\imgService.py", line 23, in getImgUrl
    return "/image/getImg?imageID="+iconID
TypeError: cannot concatenate 'str' and 'NoneType' objects
Not Found: /cms/user/url
Not Found: /cms/user/url
Not Found: /image/getImg
Internal Server Error: /image/getImg/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\py_work_space\YoYoProject\yyMongoImgManager\views.py", line 15, in getImage
    imageInfo = YYImgInfo.objects.get(pk=imgID)
  File "D:\Python27\lib\site-packages\mongoengine\queryset\base.py", line 186, in get
    raise queryset._document.DoesNotExist(msg)
DoesNotExist: YYImgInfo matching query does not exist.
Internal Server Error: /image/getImg/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\py_work_space\YoYoProject\yyMongoImgManager\views.py", line 15, in getImage
    imageInfo = YYImgInfo.objects.get(pk=imgID)
  File "D:\Python27\lib\site-packages\mongoengine\queryset\base.py", line 186, in get
    raise queryset._document.DoesNotExist(msg)
DoesNotExist: YYImgInfo matching query does not exist.
Internal Server Error: /image/getImg/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\py_work_space\YoYoProject\yyMongoImgManager\views.py", line 15, in getImage
    imageInfo = YYImgInfo.objects.get(pk=imgID)
  File "D:\Python27\lib\site-packages\mongoengine\queryset\base.py", line 186, in get
    raise queryset._document.DoesNotExist(msg)
DoesNotExist: YYImgInfo matching query does not exist.
Not Found: /cms/user/url
Not Found: /cms/user/url
Not Found: /cms/user/url
Not Found: /cms/user/url
Not Found: /cms/user/url
